# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20180613_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
