# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_customerdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Order'),
        ),
    ]
