# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20180614_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecom.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='Cart',
            new_name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Cart',
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.Cartm'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecom.Cartm'),
            preserve_default=False,
        ),
    ]
