# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20180615_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='cartm',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartorder', to='ecom.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.CustomerDetail'),
        ),
    ]
